import type { FieldType } from './submission';

export const DRAFT_SCHEMA_VERSION = 1;

export interface DraftField {
  id: string;
  label: string;
  value: string;
  fieldType: FieldType;
  updatedAt: string; // ISO 8601
  revision?: number;
  clientTimestamp?: number;
}

export interface FormDraft {
  /**
   * Primary persistent draft identity.
   * Format: `${origin}|${pathname}` or `${origin}|${pathname}|${formFamilyKey}`
   * Remains STABLE across SPA steps, re-renders, and dynamic question rendering.
   */
  id: string;
  schemaVersion: number;
  origin: string; // Normalized origin, e.g. "https://example.com"
  hostname: string; // e.g. "example.com"
  pathname: string; // Normalized pathname, e.g. "/apply/form1"
  /**
   * Optional stable container/family identifier (e.g. form action or stable form name).
   * Distinguishes two genuinely different forms on the same path without depending on field lists.
   */
  formFamilyKey?: string;
  pageTitle: string;
  pageUrl: string;
  /**
   * Structural matching & diagnostic metadata.
   * NOTE: FormFingerprint is NOT record identity. It represents the latest seen DOM structure
   * for restore confidence, change detection, and diagnostics.
   */
  formFingerprint: string;
  createdAt: string; // ISO 8601
  updatedAt: string; // ISO 8601
  fields: Record<string, DraftField>; // Keyed by normalized label or field key
}

const TRACKING_PARAMS = [
  'utm_source',
  'utm_medium',
  'utm_campaign',
  'utm_term',
  'utm_content',
  'ref',
  'fbclid',
  'gclid',
  'msclkid',
  '_ga',
  'mc_cid',
  'mc_eid',
];

/**
 * Strips tracking query parameters and normalizes a pathname or URL for stable draft matching.
 */
export function normalizeDraftPathname(rawUrlOrPath: string): string {
  if (!rawUrlOrPath) return '/';
  try {
    const url = new URL(rawUrlOrPath, 'https://dummy.local');
    for (const param of TRACKING_PARAMS) {
      url.searchParams.delete(param);
    }
    const search = url.searchParams.toString();
    return url.pathname + (search ? `?${search}` : '');
  } catch {
    const clean = rawUrlOrPath.split('#')[0] || '/';
    return clean;
  }
}

/**
 * Checks if a string looks like a volatile, autogenerated ID, random hash, or framework counter.
 */
export function isVolatileId(id: string): boolean {
  if (!id) return true;
  const trimmed = id.trim();
  // Framework prefixes: :r1:, react-aria-, ember123, etc.
  if (/^(:r\w+:|react-aria|ember\d+|__BVID__|ng-|v-\w+)/i.test(trimmed)) return true;
  // Pure numbers
  if (/^\d+$/.test(trimmed)) return true;
  // Random hex hashes (> 6 hex chars) or UUIDs
  if (/^[a-f0-9]{8,}(-[a-f0-9]{4,})*$/i.test(trimmed)) return true;
  // Too short
  if (trimmed.length < 3) return true;
  return false;
}

/**
 * Extracts a stable form-family key from container metadata when available.
 * Returns empty string if no trustworthy stable identifier exists.
 */
export function extractFormFamilyKey(container: Element | null | undefined): string {
  if (!container) return '';

  // 1. Form action (cleaned of query params/hashes and normalized)
  if (container instanceof HTMLFormElement) {
    const action = container.getAttribute('action');
    if (action && !action.startsWith('javascript:') && action !== '#' && action !== '') {
      try {
        const parsed = new URL(action, 'https://dummy.local');
        const cleanPath = parsed.pathname.toLowerCase().trim().replace(/\/+$/, '');
        const lastPart = cleanPath.split('/').pop() || '';
        if (cleanPath && cleanPath !== '/' && cleanPath !== '/#' && !isVolatileId(lastPart)) {
          return `action:${cleanPath}`;
        }
      } catch {
        // ignore invalid url
      }
    }
  }

  // 2. Semantic form name if stable
  const name = container.getAttribute('name');
  if (name && !isVolatileId(name)) {
    return `name:${name.toLowerCase().trim()}`;
  }

  // 3. Semantic form id if stable
  const id = container.getAttribute('id');
  if (id && !isVolatileId(id)) {
    return `id:${id.toLowerCase().trim()}`;
  }

  // 4. Stable aria-label on container
  const ariaLabel = container.getAttribute('aria-label');
  if (
    ariaLabel &&
    ariaLabel.trim().length >= 3 &&
    ariaLabel.length <= 60 &&
    !isVolatileId(ariaLabel)
  ) {
    const norm = ariaLabel
      .toLowerCase()
      .trim()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');
    if (norm) return `label:${norm}`;
  }

  return '';
}

/**
 * Builds the stable composite identity for a form draft.
 * Format: `${origin}|${pathname}` or `${origin}|${pathname}|${formFamilyKey}`
 *
 * NOTE: The formFingerprint MUST NOT be used as the primary identity, because
 * multi-step forms and dynamic SPAs change their fingerprint as fields appear/disappear.
 */
export function buildDraftId(origin: string, pathname: string, formFamilyKey?: string): string {
  const normOrigin = (origin || '').toLowerCase().trim().replace(/\/+$/, '');
  const normPath = normalizeDraftPathname(pathname);
  const cleanFamily = (formFamilyKey || '').trim().toLowerCase();
  return cleanFamily ? `${normOrigin}|${normPath}|${cleanFamily}` : `${normOrigin}|${normPath}`;
}
